using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.5.987.0")]
[assembly: AssemblyFileVersionAttribute("1.5.987.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © MVC Contrib 2007-2009")]
[assembly: AssemblyProductAttribute("MVCContrib 1.5 RC")]
[assembly: AssemblyCompanyAttribute("MVC Contrib")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("1.5.987.0")]

